name: Package CMS
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the src folder
        run: |
          cd src
          zip -r ../cms-latest.zip .
          
      - name: Upload Zip to a "Latest" Release
        uses: softprops/action-gh-release@v2
        with:
          files: cms-latest.zip
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
